const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
dotenv.config();
const app = express();
app.use(express.json());
app.use(cors());
const users = new Map();
const generateStockData = (ticker) => ({ ticker: ticker.toUpperCase(), price: (Math.random() * 200 + 10).toFixed(2), change: ((Math.random() - 0.5) * 20).toFixed(2), rsi: (Math.random() * 100).toFixed(1), signal: (Math.random() * 100).toFixed(0) });
app.post('/api/auth/register', async (req, res) => { const { email, password, name } = req.body; if (users.has(email)) return res.status(400).json({ error: 'User exists' }); const hashedPassword = await bcrypt.hash(password, 10); const userId = 'user_' + Date.now(); users.set(email, { id: userId, email, password: hashedPassword, name, plan: 'free' }); const token = jwt.sign({ userId, email }, 'secret'); res.json({ token, user: { id: userId, email, name, plan: 'free' } }); });
app.post('/api/auth/login', async (req, res) => { const { email, password } = req.body; const user = users.get(email); if (!user) return res.status(401).json({ error: 'Invalid' }); const valid = await bcrypt.compare(password, user.password); if (!valid) return res.status(401).json({ error: 'Invalid' }); const token = jwt.sign({ userId: user.id, email }, 'secret'); res.json({ token, user: { id: user.id, email: user.email, name: user.name, plan: user.plan } }); });
const verifyToken = (req, res, next) => { const token = req.headers.authorization?.split(' ')[1]; if (!token) return res.status(401).json({ error: 'No token' }); try { const decoded = jwt.verify(token, 'secret'); req.user = decoded; next(); } catch (err) { res.status(401).json({ error: 'Invalid' }); } };
app.post('/api/scan', verifyToken, (req, res) => { const { tickers } = req.body; const results = tickers.map(t => generateStockData(t)); res.json({ results }); });
app.get('/api/user', verifyToken, (req, res) => { const user = Array.from(users.values()).find(u => u.id === req.user.userId); res.json({ id: user.id, email: user.email, name: user.name, plan: user.plan }); });
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
const PORT = process.env.PORT || 5001;
app.listen(PORT, () => console.log(`🎯 Running on :${PORT}`));
